apiVersion: v1
kind: Namespace
metadata:
  name: hakawi
  labels:
    name: hakawi
    environment: REPLACE_ENV
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    name: ingress-nginx