/**
 * The narrow logging surface `DegradationTracker` needs. Declared structurally rather
 * than as the injected `WinstonLoggerService` (Principle #7) so a caller can pass the
 * real logger, a Nest `Logger` adapter, or a test double, and so this module has no
 * dependency on a concrete logger implementation.
 */
export interface DegradationSink {
  warn(message: string, context: string): void;
  info(message: string, context: string): void;
}

export interface DegradationSnapshot {
  /** True for as long as the component is running on its fallback path. */
  readonly degraded: boolean;
  /**
   * Stable for the whole episode and repeated on every log line, so one grep
   * reconstructs an entire outage. Null while healthy.
   */
  readonly degradationId: string | null;
  readonly degradedSinceMs: number | null;
  /** Fallback-path events since the episode started. */
  readonly degradedEvents: number;
  /** Episodes since boot. Non-zero means the alert has fired at least once. */
  readonly degradationCount: number;
}

/**
 * Makes a fail-open degradation LOUD instead of silent.
 *
 * ## Why this class exists
 *
 * Two security controls in this codebase degrade rather than fail closed, on purpose,
 * because their dependencies are shared infrastructure and an outage must not take the
 * whole API down:
 *
 * - the rate limiter falls back from Valkey to per-process in-memory counters;
 * - the WAF IP blocklist falls back to "not blocked" and skips violation escalation.
 *
 * Both are availability/security trade-offs, and both are the kind that rot into
 * "we never noticed". A fallback that emits nothing is indistinguishable from a
 * fallback that is not happening, so an alert can never be written against it. This
 * tracker emits exactly one WARN per episode — repeated lines would bury the one an
 * alert watches for — plus one INFO on recovery, and it exposes a snapshot so an
 * operator can also scrape the state instead of parsing logs.
 */
export class DegradationTracker {
  private degradationId: string | null = null;
  private degradedSinceMs: number | null = null;
  private degradedEvents = 0;
  private degradationCount = 0;

  constructor(
    private readonly sink: DegradationSink,
    /** Stable handle for one episode, generated by the caller so the id format is owned there. */
    private readonly newId: () => string,
    private readonly now: () => number = () => Date.now(),
  ) {}

  get isDegraded(): boolean {
    return this.degradationId !== null;
  }

  snapshot(): DegradationSnapshot {
    return {
      degraded: this.degradationId !== null,
      degradationId: this.degradationId,
      degradedSinceMs: this.degradedSinceMs,
      degradedEvents: this.degradedEvents,
      degradationCount: this.degradationCount,
    };
  }

  /**
   * Record that the component is now on its fallback path.
   *
   * `securityImpact` is required and must state what an attacker gains, because
   * "degraded" on its own is not something anyone pages on. The first call of an
   * episode logs at WARN; later calls of the same episode are a no-op, because the
   * event count is maintained by `countEvent` and a repeated line per probe would bury
   * the one an alert watches for.
   */
  enter(context: string, cause: string, securityImpact: string, error?: unknown): void {
    if (this.degradationId !== null) {
      return;
    }
    this.degradationId = this.newId();
    this.degradedSinceMs = this.now();
    // Opening the episode is not itself a fallback event; callers report events with
    // `countEvent`, so the two never double-count.
    this.degradedEvents = 0;
    this.degradationCount += 1;
    this.sink.warn(
      `${context} is DEGRADED (degradationId=${this.degradationId}). ${securityImpact} ` +
        `Alert on this line. cause=${cause}${error === undefined ? '' : ` error=${String(error)}`}`,
      context,
    );
  }

  /** Record a fallback-path event without opening a new episode. */
  countEvent(): void {
    this.degradedEvents += 1;
  }

  /** Close the episode, if one is open. Safe to call on the healthy path. */
  leave(context: string, recoveredTo: string): void {
    if (this.degradationId === null) {
      return;
    }
    this.sink.info(
      `${context} recovered to ${recoveredTo} (degradationId=${this.degradationId}, ` +
        `downtimeMs=${this.now() - (this.degradedSinceMs ?? this.now())}, ` +
        `fallbackEvents=${this.degradedEvents})`,
      context,
    );
    this.degradationId = null;
    this.degradedSinceMs = null;
    this.degradedEvents = 0;
  }
}
