{{- if .Values.externalSecrets.enabled -}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "frontend.fullname" . }}-secrets
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
    environment: {{ .Values.env.environment | default "production" }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ include "frontend.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: api.url
      remoteRef:
        key: {{ .Values.externalSecrets.secretPrefix }}/frontend/api-url
{{- end }}